<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net9.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="EdgeTtsSharp" Version="2.0.7" />
		<PackageReference Include="NAudio" Version="3.1.0" />
		<PackageReference Include="NWaves" Version="0.9.6" />
		<PackageReference Include="Xabe.FFmpeg" Version="6.1.1" />
	</ItemGroup>
	<ItemGroup>
		<None Update="ffmpeg.exe">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="ffplay.exe">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="ffprobe.exe">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>
</Project>
